version: "3"

services:
  app:
    build: ./
    command: bash -c "yarn && yarn dev"
    ports:
      - "3000-3001:3000-3001"
    volumes:
      - ./:/app
    environment:
      API: ${API}
      GMAPS_KEY: ${GMAPS_KEY}
