version: "3.7"

services:
  app:
    build: .
    command: sh -c "yarn && yarn dev"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      API: ${API:-http://localhost:3001}

  api:
    image: node:alpine
    command: sh -c "yarn && yarn start"
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
