version: "3"

services:
  app:
    build: ./
    container_name: travy
    command: bash -c "yarn && yarn dev"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      API: ${API}
